### ISSUE TITLE
Spelling Mistake : instead of 'Providing' , it should be 'Provided'

### ISSUE THREAD

**Issue by tyagiakhilesh** [JakobKallin/Excess-XSS#3]
From this link: http://excess-xss.com/#xss-prevention

How to enable CSP

By default, browsers do not enforce CSP. To enable CSP on your website, pages must be served with an additional HTTP header: Content‑Security‑Policy. Any page served with this header will have its security policy respected by the browser loading it, _providing_ that the browser supports CSP.

_provided_ that the browser supports CSP.

**Comment by JakobKallin** [comment]
I couldn't find a source saying that "providing" is expressly wrong, but "provided" certainly seems more conventional. Good catch. Fixed in 204e07277ea385520118a8c418af526bfa28d24a.
